version: '3' # version of docker-composeservices: # defining service/s
services:
  node-api: # name of the service
    build: .  # directory what to build, here it is root directory
    image: nodejs
    container_name : api
    restart: always
    ports:
      - $PORT:$PORT # defining port for our app
    depends_on:
      - cinedb
    networks:
      - app-network
    command: sh -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh -t 0 cinedb:3306 && npm run typeorm -- migration:run && npm run tsoa:gen && npm start"
  cinedb:
    image: mysql:latest
    restart: always
    container_name: cinedb
    env_file: ./.env
    ports:
      - $DB_PORT:$DB_PORT
    expose:
      - $DB_PORT
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - cinedb:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  cinedb: